# Branch Protection Rules
# Applies to main and develop branches

# Required status checks that must pass before merging
required_status_checks:
  strict: true  # Require branches to be up to date before merging
  contexts:
    - "ci-base"
    - "security-scan"
    - "code-review"

# Require pull request reviews before merging
required_pull_request_reviews:
  required_approving_review_count: 1
  require_code_owner_reviews: true
  dismiss_stale_reviews: true
  require_last_push_approval: true

# Restrict who can push to matching branches
restrictions:
  # Add team slugs or user logins that can push directly to protected branches
  # Example:
  # teams: [ "maintainers" ]
  # users: [ "admin1", "admin2" ]

# Other protection rules
enforce_admins: false  # Set to true to enforce these rules even for admins
allow_force_pushes: false
allow_deletions: false
required_linear_history: true

# Require conversation resolution before merging
required_conversation_resolution: true

# Require signed commits
required_signatures: false  # Set to true to require signed commits

# Lock branch (prevents all changes including from admins)
lock_branch: false

# Allow specific actors to bypass required pull requests
default_to_administrative: false
