_format_version: "3.0"
_transform: true

services:
  - name: opendiscourse-api
    url: http://opendiscourse-api:3000
    routes:
      - name: api-route
        paths:
          - "/api"
        strip_path: false
  
  - name: supabase-auth
    url: http://supabase-auth:9999
    routes:
      - name: auth-route
        paths:
          - "/auth"
        strip_path: true
  
  - name: grafana
    url: http://grafana:3000
    routes:
      - name: grafana-route
        paths:
          - "/grafana"
        strip_path: true
  
  - name: prometheus
    url: http://prometheus:9090
    routes:
      - name: prometheus-route
        paths:
          - "/prometheus"
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
  
  - name: rate-limiting
    config:
      second: 100
      minute: 1000
      hour: 10000