name: AI Code Review and Improvements

on:
  schedule:
    # Run weekly on Sundays
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope of the analysis (all, code-review, docs, quality, improvements)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - code-review
          - docs
          - quality
          - improvements

jobs:
  analyze:
    name: Run AI Code Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ai_crew/requirements.txt
    
    - name: Run AI Analysis Crew
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m ai_crew.run_analysis \
          --repo-path . \
          --scope ${{ github.event.inputs.scope || 'all' }} \
          --create-pr
    
    - name: Upload Analysis Report
      uses: actions/upload-artifact@v3
      with:
        name: ai-analysis-report
        path: ai_crew/reports/
        retention-days: 7
    
    - name: Notify on completion
      if: always()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "AI Code Analysis ${{ job.status }}"
        SLACK_MESSAGE: "AI code analysis completed with status: ${{ job.status }}"
        SLACK_COLOR: ${{ job.status == 'success' && '#36a64f' || '#ff0000' }}
