name: CI

on:
  push:
    branches: [ main, "ai/*", "*/ci-*" ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: ./ci/test.sh
      - name: Run linters and format checks
        run: ./ci/lint.sh
jobs:
    build:
        runs-on: ...
        steps:
            - uses: actions/checkout@v3

            # ... some other preparation steps (dependencies, compilation as a separate step, etc) ...

            - name: Setup Testcontainers Cloud Client
              uses: atomicjar/testcontainers-cloud-setup-action@v1
              with:
                  token: ${{ secrets.TC_CLOUD_TOKEN }}

            # ... existing steps executing your Testcontainers tests go here ...