name: Secret Scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0' # weekly

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run secret scan script
        run: ./ci/secret_scan.sh
